language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
script:
- "./build.sh"
env:
  global:
    #FTP_USER
  - secure: bAVsm4H5Kh2/ac/reztswoM81rg6hF38KPvk5MwO6pBPImbyRlrTr00RiPc5dDK/EubxpKjjSpypLEycRrj0xks2GIrOA1irnBaRWRHNZOJpJl2yNDMmJ49VlfAyHwpydWRrfJ6siwHoHjJ5OoXRMthPc+O00lO2YMN0jmuZ2QVtJLiBWVxE/3EnGl1glyjsHdmhEH0JsZXJgYxyn2nXrExWjA5C0tO0P0LMrqiCuZiRzPO0O4VnnQMjMD40wtS82f1Dkjj4CefwrOc/88eP3bYRhkeIoBwiYuuO5R+PTVauHfuoT31v1y05AfbpY6w+2XzCndIJ+3q0yya9PsB8PoSUteUgIRRm5cBNxg/4bvlXDsJniRMyLsd0+Y3UXDF61N1Jo2RmOHUqBjx/QzjAjzYjQp9vUm8OVSfpFieLMp5KK6k6bVF5fds1aBpMMHrRjnbdYd9mzWXCJchdrWgLegcYQd4L/UbfXatetomPRvuBz4aLAZdz0PEAVtwwR2eG8Uvy7pYU6hUdp3xCq4/INExMwDPdyaxmV9k8yvhDpgBmu18qP1VhD0/aaiCMXQqdLizLt6P34YRO85rayaS0bX314XJhRrhGy2PhMe19lV0VK3JyAniMQSl2s5bmLsMJyeGQaIj3KBI28y1U9EiOVGcWZwdfMCzSJ6LX/8uQPjc=
    #FTP_PASSWORD
  - secure: k90KInQN+VNnBhlq6L058G/0uz0AQp3U1LJeEF/6+VAxSeqVUBnw3lcmAUWEXc1woshZj1f8Ru2aXHVhzZzBIOFMKX/O+BL4zSym8pmniNBI8nbnMLJ5nsfEp5DgFgi5Gkq3yyPzAe08heiilyJY4OE1hvyiTvZwYM8YOrbJnzu4ZT86cunA/gQrlqhxawWxNfC6dvuci6OLeQILHHQzAVv+1ujuSy+4k9iW6EbPgfjNHFGAVREU7H8fzTfcxWKXhNl8H0XKkctzPGKyZ4OrhxU1zWBb6qzoN/Tcf14XKZdymvU4RVAUDjSyfbt3To/2EK1INClOXNNxm1u/Ern4GqVsgSDRW/AyTBQDl7hnjEZpc1ha2Yg5RBPPQD1cM03/viuGexYSOs4cZQEP68jI3/vZgVuzxfaMG1qwtkeoWci0H0jAyGj3rnQ11mN1248XytPyrpHrZQ5AqD0+i9Lo1oFmVnF+uPNXNO0XrmE13emrO1C+tC6XFsqlDhf6YUOiKoAk38OTjWhaAfDh0cgh3D0Lrj7gSisGTzhxyfYJK5bENojLzDqFQNKUQ2TznT9QGJAXW6bvvvC72ce3yFVVOL6DAHeZBXrbXJTW8+cvTqt1VxRItRHbbQOAmi5B//WmOzVV+r+Z6fG2Mxq7QQFrqFcUWE20GYRK5zyHRP8Jzyg=
    #FTP_HOST
  - secure: OGj1TmURHb/aG2VapirLPy9z++m1nWKyCPxv+2ifsth3mjM+2xr3zr81XGSNvhNLgxg1XMlXYPHSkv9h9/8gJ1cuO27sKmP4tggdwRBQey1N0qk/9+pfFaNxalOkM0W/0VT4jIYRGfLYUox0nPl4S2MVpZTS7Vinb7+5N/fH+OlkeUr+DA7dNtdkYKX+0S1ScKhTnaY4GtmhL+nr1RBiz1tUUle4cscRpzs8ft6RZpxnkEEIQIppo1QGyxMvTd/+anjk+ANAQ0SuZ2klkAWORMbZWD2e9v964lYg7GDNUQD1vgaVho44R5J6+azTuu5emGSWfDXdgGg2veVz5LkxPA8YEIAeXfWd46TDyjVEnXuwHo+nxKr0VSWzPk2XV6haqtIBUertn9ASCEBmipDCsYjqTk1+WEgJpbfI3jN/7kOCR8pTRiF2Ha8KSn3domBtkKtkhRk5DllfzJ3nTP11mUXIh0ZDDSQI0cLJF4gvY1qsXTeuioq1PHqsnzl+aCEyxwpZwVxa1k1GyyL63uRO7jjV0slydKwETSNQemuQeKdW3JMTxs2MQ9jaGDkHdbL3SS/ogP1+Z7lXbt3WWmQP90ZYN+2skQATBd1+JiwU+qwyIZ+C5lxbABeeP96pOyI7p+aiCamoCVZ1N8l7R7yhy+tB59fUBQ2JP5mps30aQqM=
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master