# overrides for local development (outside of Visual Studio)

version: "3.8"

services:
  reverse_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/conf.d.dev:/etc/nginx/conf.d:ro
      
  directory.db:
    command: ["postgres", "-c", "log_statement=all"]