# overrides for local development (outside of Visual Studio)

version: "3.8"

services:
  reverse_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - reverse_proxy
    depends_on:
      - web
      - directory.api
    volumes:
      - ./reverse-proxy/svr-includes:/etc/nginx/svr-includes:ro
      - ./reverse-proxy/conf.d.dev:/etc/nginx/conf.d:ro
