export interface IList {
    id: number;
    chatUrl: string;
    description: string;
    descriptionSourceUrl: string;
    donateUrl: string;
    emailAddress: string;
    forumUrl: string;
    homeUrl: string;
    issuesUrl: string;
    languageIds: number[];
    licenseId: number;
    maintainerIds: number[];
    name: string;
    policyUrl: string;
    publishedDate: string;
    //ruleCount: number;
    submissionUrl: string;
    syntaxId: number;
    tagIds: number[];
    //updatedDate: string;
    viewUrl: string;
    viewUrlMirrors: string[];
};