# overrides for production build
# https://github.com/docker/compose/issues/4047

version: "3.7"

services:
  directory-api:
    build:
      context: ../services
      dockerfile: Directory/FilterLists.Directory.Api/Dockerfile

  web:
    build:
      context: ../web
