# for integration testing directory migrations

version: "3.7"

services:
  directory-migrations-tests:
    build:
      context: ../services
      dockerfile: Directory/FilterLists.Directory.Api/migrate.Dockerfile
      target: test-migrations
    volumes:
      - directory-migrations-tests-results:/FilterLists.Directory.Infrastructure.Migrations.Tests/TestResults
    depends_on:
      - directory-db
    env_file:
      - directory-api.env

  directory-db:
    image: postgres:alpine
    env_file:
      - directory-db.env

volumes:
  directory-migrations-tests-results:
    external: true
