version: "3.7"

services:
  reverse-proxy:
    image: nginx:alpine
    restart: always
    networks:
      - reverse-proxy

  api-docs:
    image: swaggerapi/swagger-ui:latest
    restart: always
    networks:
      - reverse-proxy
    depends_on:
      - directory-api
    env_file:
      - api-docs.env

  archival-api:
    image: ghcr.io/collinbarrett/filterlists-archival-api
    restart: always
    networks:
      - reverse-proxy
      - archival
    depends_on:
      - archival-scheduling-db
    volumes:
      - archival-application-insights:/app/${ARCHIVAL_APPLICATION_INSIGHTS_SERVER_TELEMETRY_CHANNEL_STORAGE_PATH}
      - archival-archives:/app/${ARCHIVAL_GIT_REPOSITORY_PATH}
    env_file:
      - archival-api.env
    environment:
      ApplicationInsights__ServerTelemetryChannelStoragePath: ${ARCHIVAL_APPLICATION_INSIGHTS_SERVER_TELEMETRY_CHANNEL_STORAGE_PATH}
      Api__DirectoryHost: ${DIRECTORY_HOST}
      Git__RepositoryPath: ${ARCHIVAL_GIT_REPOSITORY_PATH}

  archival-scheduling-db:
    image: redis:alpine
    restart: always
    networks:
      - archival
    volumes:
      - archival-scheduling-db:/data
    entrypoint: ["redis-server", "--appendonly", "yes"]

  directory-api:
    image: ghcr.io/collinbarrett/filterlists-directory-api
    restart: always
    networks:
      reverse-proxy:
        aliases:
          - ${DIRECTORY_HOST}
      directory:
    depends_on:
      - directory-db
    volumes:
      - directory-application-insights:/app/${DIRECTORY_APPLICATION_INSIGHTS_SERVER_TELEMETRY_CHANNEL_STORAGE_PATH}
    env_file:
      - directory-api.env
    environment:
      ApplicationInsights__ServerTelemetryChannelStoragePath: ${DIRECTORY_APPLICATION_INSIGHTS_SERVER_TELEMETRY_CHANNEL_STORAGE_PATH}

  directory-db:
    image: postgres:alpine
    restart: always
    networks:
      - directory
    volumes:
      - directory-db:/var/lib/postgresql/data
    env_file:
      - directory-db.env

networks:
  reverse-proxy:
  archival:
  directory:

volumes:
  archival-application-insights:
  archival-scheduling-db:
  archival-archives:
  directory-application-insights:
  directory-db:
