version: "3.7"

services:
  reverse-proxy:
    image: nginx:alpine
    restart: always
    networks:
      - reverse-proxy
    depends_on:
      - api-docs
      - directory-api

  api-docs:
    image: swaggerapi/swagger-ui:latest
    restart: always
    networks:
      - reverse-proxy
    depends_on:
      - directory-api
    env_file:
      - api-docs.env

  directory-api:
    image: ghcr.io/collinbarrett/filterlists-directory-api
    restart: always
    networks:
      reverse-proxy:
        aliases:
          - ${DIRECTORY_HOST}
      directory:
    depends_on:
      - directory-db
    volumes:
      - directory-application-insights:/app/${DIRECTORY_APPLICATION_INSIGHTS_SERVER_TELEMETRY_CHANNEL_STORAGE_PATH}
    env_file:
      - directory-api.env
    environment:
      ApplicationInsights__ServerTelemetryChannelStoragePath: ${DIRECTORY_APPLICATION_INSIGHTS_SERVER_TELEMETRY_CHANNEL_STORAGE_PATH}

  directory-db:
    image: postgres:alpine
    restart: always
    networks:
      - directory
    volumes:
      - directory-db:/var/lib/postgresql/data
    env_file:
      - directory-db.env

networks:
  reverse-proxy:
  directory:

volumes:
  directory-application-insights:
  directory-db:
