trigger:
  batch: false
  branches:
    include: [main]
  paths:
    include:
      [
        reverse-proxy/*,
        docker-compose/docker-compose.yml,
        docker-compose/docker-compose.prod.yml,
      ]

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 5

  - task: CopyFiles@2
    displayName: stage config files
    inputs:
      Contents: |
        reverse-proxy/server-includes/*
        reverse-proxy/location-includes/*
        reverse-proxy/conf.d/*
      TargetFolder: $(Build.ArtifactStagingDirectory)
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

  - task: CopyFiles@2
    displayName: stage docker-compose files
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/docker-compose
      Contents: |
        docker-compose.yml
        docker-compose.prod.yml
      TargetFolder: $(Build.ArtifactStagingDirectory)
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  - task: PublishBuildArtifacts@1
    displayName: publish files
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: drop
      publishLocation: Container
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
