trigger:
  batch: false
  branches:
    include: [master]
  paths:
    include: [reverse-proxy/*, docker-compose.yml, docker-compose.prod.yml]

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: CopyFiles@2
    displayName: stage files
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: |
        reverse-proxy/*
        docker-compose.yml
        docker-compose.prod.yml
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: true
      OverWrite: true
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - task: PublishBuildArtifacts@1
    displayName: publish files
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: drop
      publishLocation: Container
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
