name: web Build and Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - vNext
    paths:
      - web/**
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - vNext
    paths:
      - web/**

jobs:
  build_and_deploy:
    if: github.event.pull_request.user.login != 'dependabot[bot]' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed'))
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Fetch
        uses: actions/checkout@v4
      # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
      - name: Next.js Build Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/web/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_BAY_0D2FFAA0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          # https://aka.ms/swaworkflowconfig
          app_location: /web
          api_location: ""
          output_location: ""
        env:
          NEXT_TELEMETRY_DISABLED: 1 # https://nextjs.org/telemetry

  close_pull_request:
    if: github.event.pull_request.user.login != 'dependabot[bot]' && github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_BAY_0D2FFAA0F }}
          action: close