name: FilterLists Web Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - vNext
    paths:
      - web/**
      - api/**
      - .github/workflows/azure-static-web-apps-lemon-stone-084516c10.yml
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - vNext
    paths:
      - web/**
      - api/**
      - .github/workflows/azure-static-web-apps-lemon-stone-084516c10.yml

jobs:
  build_web:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: npx prettier --check .

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test-headless

      - name: Build
        run: npm run build

      - name: Copy SWA config to artifacts
        run: cp staticwebapp.config.json dist/web/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-artifacts
          path: web/dist/web/*

  build_api:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Publish
        run: dotnet publish FilterLists.Api/FilterLists.Api.csproj -c Release -r win-x86 -p:PublishReadyToRun=true --no-self-contained

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-artifacts
          path: api/FilterLists.Api/bin/Release/net6.0/win-x86/publish/*

  deploy_swa:
    needs: [build_web, build_api]
    name: Deploy SWA
    runs-on: ubuntu-latest
    steps:
      - name: Download workflow artifacts
        uses: actions/download-artifact@v3

      - name: Deploy SWA
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_STONE_084516C10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          skip_app_build: true
          app_location: '/web-artifacts'
          skip_api_build: true
          api_location: '/api-artifacts'

          # dependabot (and possibly other non-Contributors?) don't have the secret on their PR workflow run
          skip_deploy_on_missing_secrets: true

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Remove SWA staging for PR
    runs-on: ubuntu-latest
    steps:
      - name: Close PR
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_STONE_084516C10 }}
          action: 'close'
