name: Web - Build & Deploy

on:
  push:
    branches:
      - next
    paths:
      - .github/workflows/web.yml
      - web/**
  pull_request:
    branches:
      - next
    paths:
      - .github/workflows/web.yml
      - web/**

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REPOSITORY: ${{ github.repository_owner }}/filterlists-web
  CONTAINER_IMAGE_TAG_UNIQUE: ${{ github.run_id }}
  WORKING_DIRECTORY: ./web

jobs:
  build:
    name: Build & Push Docker Image

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKING_DIRECTORY }}
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REPOSITORY }}:${{ env.CONTAINER_IMAGE_TAG_UNIQUE }}
            ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    needs: build

    if: github.event_name == 'push'

    env:
      AZURE_WEBAPP_NAME: app-filterlists-web-prod

    environment:
      name: production-web-next
      url: https://next.filterlists.com

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_APP_FILTERLISTS_WEB_PROD }}
          images: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REPOSITORY }}:${{ env.CONTAINER_IMAGE_TAG_UNIQUE }}
