name: Web - Build & Deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/web.yml
      - web/**
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - .github/workflows/web.yml
      - web/**

jobs:
  build_and_deploy_staging:
    name: Build & Deploy to Staging

    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' && github.event.action != 'closed'

    environment:
      name: staging-web
      url: ${{ steps.builddeploy.outputs.static_web_app_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install
        run: npm ci
        working-directory: ./web

      - name: Run Prettier
        run: npm run prettier:check
        working-directory: ./web

      - name: Run ESLint
        run: npm run eslint:check
        working-directory: ./web

      - name: Build
        run: npm run build
        working-directory: ./web

      - name: Copy Static Web App Config
        run: cp staticwebapp.config.json build/
        working-directory: ./web

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAPP_FILTERLISTS_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: ./web/build
          output_location: ""
          skip_app_build: true
        continue-on-error: true

  build_and_deploy_production:
    name: Build & Deploy to Production

    runs-on: ubuntu-latest

    if: github.event_name == 'push'

    environment:
      name: production-web
      url: https://filterlists.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install
        run: npm ci
        working-directory: ./web

      - name: Build
        run: npm run build
        working-directory: ./web

      - name: Copy Static Web App Config
        run: cp staticwebapp.config.json build/
        working-directory: ./web

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAPP_FILTERLISTS_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: ./web/build
          output_location: ""
          skip_app_build: true

  close_pull_request:
    name: Close Pull Request

    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' && github.event.action == 'closed'

    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAPP_FILTERLISTS_PROD }}
          action: close
          app_location: ./web
